services:
  api:
    build: .
    container_name: regime_fiscal_api
    restart: always
    ports:
      - "80:8000" # Mapeia a porta 80 da sua máquina para a porta 8000 interna do FastAPI
    volumes:
      - ./database.db:/app/database.db
    networks:
      - rede_local

networks:
  rede_local:
    driver: bridge